input BlockObjectInput {
  hash: String!
  number: Int!
}

type CreateBlockResponse {
  hash: String!
  number: Int!
}

type CreateTransactionResponse {
  from: String!
  hash: String!
  to: String
}

type Mutation

type Query {
  block(hash: String!): CreateBlockResponse!
  blocks: [CreateBlockResponse!]!
  transaction(hash: String!): CreateTransactionResponse!
  transactions: [CreateTransactionResponse!]!
}

input TransactionObjectInput {
  from: String!
  hash: String!
  to: String
}