input BlockObjectInput {
  hash: String!
  number: Int!
}

type CreateBlockResponse {
  hash: String!
  number: Int!
}

type CreateTransactionResponse {
  from: String!
  hash: String!
  to: String
}

type Mutation {
  create_block(input: BlockObjectInput!): CreateBlockResponse!
  create_transaction(input: TransactionObjectInput!): CreateTransactionResponse!
  remove_block(hash: String!): CreateBlockResponse!
  remove_transaction(hash: String!): CreateTransactionResponse!
  update_block(input: BlockObjectInput!): CreateBlockResponse!
  update_transaction(input: TransactionObjectInput!): CreateTransactionResponse!
}

type Query {
  block(hash: String!): CreateBlockResponse!
  blocks: [CreateBlockResponse!]!
  transaction(hash: String!): CreateTransactionResponse!
  transactions: [CreateTransactionResponse!]!
}

input TransactionObjectInput {
  from: String!
  hash: String!
  to: String
}